"""empty message

Revision ID: 2dd0d81b0af7
Revises: 5844fe56ba45
Create Date: 2024-08-15 15:19:58.534891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd0d81b0af7'
down_revision = '5844fe56ba45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], ),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('workout_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('log_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['workout_log.log_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_details')
    op.drop_table('workout_log')
    op.drop_table('exercises')
    op.drop_table('workout')
    # ### end Alembic commands ###
